# Generated by Django 4.2.1 on 2023-10-20 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anketa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='blank/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Бланк',
                'verbose_name_plural': 'Бланки',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['-title'],
            },
        ),
        migrations.RenameModel(
            old_name='Profession',
            new_name='Professions',
        ),
        migrations.CreateModel(
            name='Sertif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Filled_sertif', models.ImageField(blank=True, upload_to='serif/%Y/%m/%d')),
                ('Blank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.blank', verbose_name='Бланк')),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('Score', models.PositiveIntegerField()),
                ('Skills', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.skills', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Model_prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('Score', models.PositiveIntegerField()),
                ('Professions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.professions', verbose_name='Профессия')),
                ('Skills', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.skills', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Модельная профессия',
                'verbose_name_plural': 'Модельные профессии',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('Score', models.PositiveIntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Skills', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.skills', verbose_name='Навык')),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-title'],
            },
        ),
    ]
