# Generated by Django 4.2.1 on 2023-10-20 12:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('anketa', '0002_blank_skills_rename_profession_professions_sertif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('avatar', models.ImageField(blank=True, upload_to='human/%Y/%m/%d')),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Бланк',
                'verbose_name_plural': 'Бланки',
                'ordering': ['-title'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='sertif',
            name='Blank',
        ),
        migrations.RemoveField(
            model_name='sertif',
            name='Users',
        ),
        migrations.RenameField(
            model_name='blank',
            old_name='image',
            new_name='image_full',
        ),
        migrations.AddField(
            model_name='blank',
            name='image_one',
            field=models.ImageField(blank=True, upload_to='blank/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Sertif',
        ),
    ]
